### ISSUE TITLE
Align nbgallery to center

### ISSUE THREAD

**Issue by gianlucadetommaso** [kai687/sphinxawesome-theme#1091]
The output and the images created via the directive [.. nbgallery::](https://nbsphinx.readthedocs.io/en/0.7.1/a-normal-rst-file.html#thumbnail-galleries) align automatically to the left margin. Is there a way to align them to the center?

**Comment by kai687** [comment]
Hi @gianlucadetommaso :wave:. Thank you for your question! I never used `nbsphinx`. If the `nbgallery` directive doesn't accept an option for aligning the whole element, you could add custom CSS with the class of the element you want to align.
