### ISSUE TITLE
Distinguish external links

### ISSUE THREAD

**Issue by kai687** [kai687/sphinxawesome-theme#142]
All links to other resources should be marked by the conventional icon for it. I can implement this as a post-build step.

**Comment by fakerybakery** [comment]
Hi, for some reason whenever I re-build the docs, a new icon is added if the page has not changed.
Example:
![Screenshot](https://github.com/kai687/sphinxawesome-theme/assets/76186054/c3d682a1-a1fa-4e98-84e3-987697e492e7)
Is there any way to resolve this?
Thank you!
