### ISSUE TITLE
Theme breaks with Sphinx 7.2.0

### ISSUE THREAD

**Issue by kai687** [kai687/sphinxawesome-theme#1464]
Trying to build fails with Sphinx 7.2.0 with the following error:

```
Theme error:
An error happened in rendering the page index.
Reason: TypeError("argument of type '_CascadingStyleSheet' is not iterable")
```

**Comment by humitos** [comment]
We are having the same issue with the Read the Docs Sphinx Theme. See https://github.com/readthedocs/sphinx_rtd_theme/issues/1502 cc @picnixz

**Comment by DeepakArora76** [comment]
I'm eager to know when this issue will be resolved. Can you share any insights on the timeline?
