### ISSUE TITLE
Logo not shown on main page

### ISSUE THREAD

**Issue by languitar** [kai687/sphinxawesome-theme#165]
Currently, a logo configured via `html_logo` is not visible on the documentation main page. All other pages show it though.

**Comment by languitar** [comment]
Actually, the logo seems to be there but is made indefinitely small due to some padding classes that do not exist on other headers.

**Comment by kai687** [comment]
Thanks for filing this issue. Yes, I applied padding to the logo on the main page by accident. That is already fixed in the master branch, but not yet in the release.

**Comment by languitar** [comment]
Would you mind pushing out a new release? That would make me switch to this theme.

**Comment by kai687** [comment]
Oh, ok. I'll tag a new release right away.

**Comment by kai687** [comment]
Should no longer be an issue in version 1.15.0
