### ISSUE TITLE
Anchor symbol missing for headings on a page

### ISSUE THREAD

**Issue by languitar** [kai687/sphinxawesome-theme#193]
Currently, the top-level heading of each page displays a chain symbol when hovering for the HTML anchor. Other headings on a page also have such an anchor but the symbol is not shown on hover. This is a bit inconsistent.

**Comment by kai687** [comment]
I can see that only on the 'on-page navigation' page in my preview. On other pages, this works as intended. Maybe there's something when you use `contents` on a page (as on the page `on-page navigation` because otherwise, I don't use that directive. Weird, but I'll check.

**Comment by kai687** [comment]
Yup, seems like a consequence of the different origin of the `contents` directive. The structure of the headings are different when you use it. I guess in your case, the header itself becomes a link. 

Sphinx: 
```
<h2>Heading<a class="headerlink">¶</a</h2>
```

After using the `contents` directive:
```
<h2><a class="toc-backref">Heading</a><h2>
```

**Comment by languitar** [comment]
Not nice... Maybe one can still make this look similar.

**Comment by languitar** [comment]
Ah, that's also the reason for underlines on hove on these pages.

**Comment by kai687** [comment]
If you add `:backlinks: none` to the options of the `contents` directive, Sphinx's headerlink normal headerlink mechanism takes over (https://docutils.sourceforge.io/docs/ref/rst/directives.html#id55). The solution for me would be to overwrite the directive, overriding the default choice for this option.

**Comment by kai687** [comment]
Turns out I left out an important detail in my implementation of this headerlink mechanism. I didn't understand it until now, which is why I left it out. Now, this should be working fine without any modification needed by the author.
