### ISSUE TITLE
can't center-align a figure

### ISSUE THREAD

**Issue by SuryaThiru** [kai687/sphinxawesome-theme#283]
Image is always left-aligned irrespective of the argument passed for align. However, changing the theme to alabaster or classic produces a centered image.

```rst
.. figure:: logo/logo.png
   :align: center
```

Can you please help identify the issue?

**Comment by kai687** [comment]
Hi and thank you for filing this issue. I forgot to add styles for centered images. In the mean time, you can add custom CSS yourself. This is how many themes would center an image: 

```CSS
figure.align-center {
    margin: auto;
}
```

I will add this to the next version.
