### ISSUE TITLE
Content not in full width 

### ISSUE THREAD

**Issue by estyxx** [kai687/sphinxawesome-theme#308]
Hello, 

I installed the theme with the recommended setup, but the content but something seems to be broken: the sidebar is not displayed, there isn't the scroller if we use a smaller size something is show up but only at the bottom... 
Here there a couple of screenshots... 
I also try to set some options, but nothing seems change... 

<img width="1440" alt="Screenshot 2021-02-01 at 22 26 53" src="https://user-images.githubusercontent.com/28976199/106526152-66ce0c00-64e5-11eb-9c17-4119a59a0853.png">
<img width="723" alt="Screenshot 2021-02-01 at 22 30 37" src="https://user-images.githubusercontent.com/28976199/106526566-2458ff00-64e6-11eb-8512-680ee3c02082.png">

**Comment by kai687** [comment]
Hmmm, that looks totally off. That looks like the mobile view (with the menu at the bottom) is visible on large screens. Is this publically available for me to take a look at? If not, are you using any customizations, like custom templates, custom CSS, custom JavaScript?

**Comment by estyxx** [comment]
No, unfortunately is not public. 

This is my conf.py 
```
import os
import sys

import django
import recommonmark  # noqa
from recommonmark.transform import AutoStructify
from recommonmark.parser import CommonMarkParser

sys.path.insert(0, os.path.abspath("../.."))
sys.setrecursionlimit(1500)

os.environ["DJANGO_SETTINGS_MODULE"] = "myapp.settings"


django.setup()

# -- Project information -----------------------------------------------------

project = "myapp"
...

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinxcontrib.spelling",
    "rinoh.frontend.sphinx",
    "sphinx.ext.autodoc",
    "recommonmark",
]

# Add any paths that contain templates here, relative to this directory.
# templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["**tests**", "test**"]
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "undoc-members": True,
    "private-members": True,
    "special-members": "__init__",
}


source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinxawesome_theme"
html_theme_options = {
    "nav_include_hidden": False,
    "show_nav": True,
    "show_breadcrumbs": True,
    "breadcrumbs_separator": "/",
    "show_prev_next": True,
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ["_static"]

latex_elements = {
    "papersize": "letterpaper",
    "pointsize": "10pt",
    "preamble": "",
    "figure_align": "htbp",
}


# app setup hook
assembla_url = "...."


def setup(app):
    app.add_config_value(
        "recommonmark_config",
        {
            "url_resolver": lambda url: assembla_url + url,
            "auto_toc_tree_section": "Contents",
            "enable_math": False,
            "enable_inline_math": False,
            "enable_eval_rst": True,
        },
        True,
    )
    app.add_transform(AutoStructify)
```

my _static and _templates dir are empty ... 
I'm generating the docs with sphinx `make html`, I saw there is also `make singlehtml` that is putting everything in one page and with that is working, but the content is all together...

**Comment by kai687** [comment]
Thanks for sharing these additional details. I'll look into it as soon as I can.

**Comment by kai687** [comment]
Somehow, I can't reproduce it. I created a new virtual environment, installed `sphinx==3.3.1`, `sphinxawesome-theme`, `rinohtype`, and used the `conf.py` file (except the django parts) and some dummy content, and it everything looks ok on my end. I don't really know what to suggest. I thought that something would 'mess' with the HTML structure which causes the display to be messed up, but all Sphinx extensions you use don't cause this kind of behavior. 

Is this behavior dependent on any browser/extension, or hosting? Like, some extensions or servers inject some code in the HTML and that might mess with the structure of the page. Sorry, that's all I have.

**Comment by estyxx** [comment]
Something very weird must happend... I just switch again on the docs' branch to have a try on a different browser/incognito.. and was working... o.O 
maybe some cache or old build was messed up... I have no idea, I tried a lot before opening this issue, and I didn't change so much... 
I will close this issue, sorry to bother you...

**Comment by kai687** [comment]
I'm really glad it was just a glitch and the problem doesn't exist anymore. Thanks for letting me know.
