### ISSUE TITLE
Ability to change :guilabel:

### ISSUE THREAD

**Issue by logictester** [kai687/sphinxawesome-theme#379]
Hi,
I'm trying to change the way :guilabel: is presented, right now it's not different than regular code, in RTD theme for example, it uses a white background around. Where can the :guilabel: defintion be modified? For example: make it bold
Thanks for a great theme!

**Comment by kai687** [comment]
Thanks for your kind words and thanks for creating an issue for this. It looks like a bug. Currently, there isn't any style applied at all to the `<span class="guilabel">` elements. I intended to appear in 'bold font'. I'll fix this in the next version. 

In the mean time, you can add your own CSS, e.g. place this class into a file `custom.css`:

```css
.guilabel {
  font-weight: 500;
}
```

and follow the steps mentioned here: https://sphinxawesome.xyz/how-to/modify/#add-or-override-styles
