### ISSUE TITLE
Decode error in postprocess

### ISSUE THREAD

**Issue by plinnie** [kai687/sphinxawesome-theme#386]
I'm applying your theme to our Sphinx documentation I get the following error
```
Extension error (sphinxawesome_theme.postprocess):
Handler <function post_process_html at 0x00000157905FE790> for event 'build-finished' threw an exception (exception: 'charmap' codec can't decode byte 0x9d in position 24797: character maps to <undefined>)
```
Sphinx version: 3.5.2
Python: 3.8.8 (64 bit)
Awesome-theme:  1.19.2
Platform: Window 10

The html seems to be rendered, but the end of the page shows the following:
![afbeelding](https://user-images.githubusercontent.com/22786183/113714382-9d442500-96e8-11eb-8be5-258ed771e094.png)

It doesn't seem to be related to any specific file. Even with only a toc the error persists.

**Comment by plinnie** [comment]
Appears related to double quotes. Removing all double quotes from the text solves the problem. I've tried escaping the double quotes in multiple ways, nothing helps.

**Comment by kai687** [comment]
Hi, thank you for filing this issue and testing a few conditions. I have an idea, but I'm not sure if it will address the problem, as I don't test on Windows at the moment. It looks similar to [this StackOverflow issue](https://stackoverflow.com/a/30751201), so I'll try to include the encoding as well.

**Comment by kai687** [comment]
@plinnie could you try using version 1.19.3 (I just released a bugfix that might fix this issue, but I haven't tested this on Windows yet)?

**Comment by plinnie** [comment]
This seems to have fixed things, thanks!
