### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by kai687** [kai687/sphinxawesome-theme#709]
Implement a simple dark mode that respects the user's system preferences.

**Comment by wasi-master** [comment]
Any updates on this?

**Comment by wasi-master** [comment]
I don't use tailwind but tailwind seems to have a built-in dark mode feature

https://tailwindcss.com/docs/dark-mode

**Comment by kai687** [comment]
No update on this. I don't know when I'll have the time to do anything about it, and then I need to decide if it's worth it, because it would increase the size of the final CSS file. For something so simple, the CSS file is already kind of large. 

The main effort to implement dark mode is to add the classes to each element. For every: `text-color-XXX` I need to add `dark:text-color-XXX` to specify the color an element would have in dark mode.

**Comment by wasi-master** [comment]
Oh, thanks for the details, I may try to do this myself when I get time
